name: Deploy to Portainer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

    - name: Deploy to Portainer
      run: |
        curl -X POST "http://<PORTAINER_URL>/api/endpoints/1/docker/containers/create" \
        -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{
              "Image": "${{ secrets.DOCKER_USERNAME }}/portfolio:latest",
              "name": "5_portfolio-test",
              "HostConfig": {
                "PortBindings": {
                  "80/tcp": [
                    {
                      "HostPort": "80"
                    }
                  ]
                }
              }
            }'
        curl -X POST "http://<PORTAINER_URL>/api/endpoints/1/docker/containers/portfolio/start" \
        -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}"